# 2)მომხმარებელს შემოატანინეთ ორი რიცხვი გააკეთეთ მათზე მათემატიკური ოპერაციები  ("+, -, *, /, %, <, >, <=, >=, ==, !=. **) 

num1 = int(input("enter your number"))
num2 = int(input("enter your number"))

print ( num1 + num2 )
print ( num1 - num2 )
print ( num1 * num2 )
print ( num1 / num2 )
print ( num1 % num2 )
print ( num1 < num2 )
print ( num1 > num2 )
print ( num1 <= num2 )
print ( num1 >= num2 )
print ( num1 != num2 )
print ( num1 ** num2 )